[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/sofascore-live"
  to = "/.netlify/functions/sofascore"
  status = 200

[[redirects]]
  from = "/api/config"
  to = "/.netlify/functions/config"
  status = 200

[[redirects]]
  from = "/api/contract-address"
  to = "/.netlify/functions/contract-address"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
