import { localnet, studionet, testnetAsimov } from "genlayer-js/chains";

export const chainMap = {
  localnet: localnet,
  studionet: studionet,
  testnetBradbury: testnetAsimov,
};

export const networkLabels = {
  localnet: "GenLayer localnet",
  studionet: "GenLayer studionet",
  testnetBradbury: "GenLayer testnet Bradbury",
};

export const oddsSources = [
  { name: "Pitchside Odds", variance: 4 },
  { name: "Kickoff Markets", variance: -3 },
  { name: "Fulltime Exchange", variance: 2 },
  { name: "FinalWhistle AI", variance: 0, isAi: true },
];

export const prestigeTerms = [
  "premier league", "champions league", "europa league", "la liga",
  "serie a", "bundesliga", "ligue 1", "fa cup", "carabao cup",
  "arsenal", "chelsea", "liverpool", "manchester united", "man united",
  "manchester city", "man city", "tottenham", "newcastle", "real madrid",
  "barcelona", "atletico", "bayern", "dortmund", "leverkusen",
  "psg", "marseille", "inter", "milan", "juventus", "napoli", "roma",
  "ajax", "psv", "benfica", "porto", "sporting", "celtic", "rangers",
  "sevilla", "espanyol", "almeria",
];

export const teamLogoMap = {
  "Arsenal": "https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg",
  "Chelsea": "https://upload.wikimedia.org/wikipedia/en/c/cc/Chelsea_FC.svg",
  "Liverpool": "https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg",
  "Manchester United": "https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg",
  "Man United": "https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg",
  "Manchester City": "https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg",
  "Man City": "https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg",
  "Tottenham Hotspur": "https://upload.wikimedia.org/wikipedia/en/8/8e/Tottenham_Hotspur.svg",
  "Tottenham": "https://upload.wikimedia.org/wikipedia/en/8/8e/Tottenham_Hotspur.svg",
  "Newcastle United": "https://upload.wikimedia.org/wikipedia/en/5/56/Newcastle_United_Logo.svg",
  "Newcastle": "https://upload.wikimedia.org/wikipedia/en/5/56/Newcastle_United_Logo.svg",
  "Real Madrid": "https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg",
  "Barcelona": "https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg",
  "Atletico Madrid": "https://upload.wikimedia.org/wikipedia/en/1/1b/Atletico_Madrid_logo.svg",
  "Atletico": "https://upload.wikimedia.org/wikipedia/en/1/1b/Atletico_Madrid_logo.svg",
  "Bayern Munich": "https://upload.wikimedia.org/wikipedia/en/1/1b/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg",
  "Bayern": "https://upload.wikimedia.org/wikipedia/en/1/1b/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg",
  "Borussia Dortmund": "https://upload.wikimedia.org/wikipedia/en/6/67/Borussia_Dortmund_logo.svg",
  "Dortmund": "https://upload.wikimedia.org/wikipedia/en/6/67/Borussia_Dortmund_logo.svg",
  "Paris Saint-Germain": "https://upload.wikimedia.org/wikipedia/en/a/a7/Paris_Saint-Germain_F.C..svg",
  "PSG": "https://upload.wikimedia.org/wikipedia/en/a/a7/Paris_Saint-Germain_F.C..svg",
  "Inter Milan": "https://upload.wikimedia.org/wikipedia/en/0/08/FC_Internazionale_Milano_badge.svg",
  "Inter": "https://upload.wikimedia.org/wikipedia/en/0/08/FC_Internazionale_Milano_badge.svg",
  "AC Milan": "https://upload.wikimedia.org/wikipedia/en/d/d0/AC_Milan.svg",
  "Milan": "https://upload.wikimedia.org/wikipedia/en/d/d0/AC_Milan.svg",
  "Juventus": "https://upload.wikimedia.org/wikipedia/en/d/d0/Juventus_Turin_Logo.svg",
  "Napoli": "https://upload.wikimedia.org/wikipedia/en/d/d2/SSC_Napoli_logo.svg",
  "Roma": "https://upload.wikimedia.org/wikipedia/en/c/c9/AS_Roma_logo.svg",
  "Ajax": "https://upload.wikimedia.org/wikipedia/en/de/de2/Ajax_Amsterdam.svg",
  "Benfica": "https://upload.wikimedia.org/wikipedia/en/8/89/S.L._Benfica_logo.svg",
  "Porto": "https://upload.wikimedia.org/wikipedia/en/f/f1/FC_Porto_logo.svg",
  "Sporting CP": "https://upload.wikimedia.org/wikipedia/en/7/75/Sporting_CP_logo.svg",
  "Celtic": "https://upload.wikimedia.org/wikipedia/en/7/70/Celtic_FC.svg",
  "Rangers": "https://upload.wikimedia.org/wikipedia/en/4/43/Rangers_FC.svg",
  "Sevilla": "https://upload.wikimedia.org/wikipedia/en/8/86/Sevilla_FC_logo.svg",
  "West Ham United": "https://upload.wikimedia.org/wikipedia/en/c/c2/West_Ham_United_FC.svg",
  "West Ham": "https://upload.wikimedia.org/wikipedia/en/c/c2/West_Ham_United_FC.svg",
  "Aston Villa": "https://upload.wikimedia.org/wikipedia/en/f/f9/Aston_Villa_FC_logo.svg",
  "Brighton": "https://upload.wikimedia.org/wikipedia/en/7/7c/Brighton_%26_Hove_Albion_logo.svg",
  "Brighton & Hove Albion": "https://upload.wikimedia.org/wikipedia/en/7/7c/Brighton_%26_Hove_Albion_logo.svg",
  "Bayer Leverkusen": "https://upload.wikimedia.org/wikipedia/en/5/59/Bayer_04_Leverkusen_logo.svg",
  "Leverkusen": "https://upload.wikimedia.org/wikipedia/en/5/59/Bayer_04_Leverkusen_logo.svg",
  "RB Leipzig": "https://upload.wikimedia.org/wikipedia/en/d/d3/RB_Leipzig_logo.svg",
  "Atalanta": "https://upload.wikimedia.org/wikipedia/en/4/4c/Atalanta_B.C._logo.svg",
  "Lazio": "https://upload.wikimedia.org/wikipedia/en/5/57/SS_Lazio_2023.svg",
  "Fiorentina": "https://upload.wikimedia.org/wikipedia/en/9/96/ACF_Fiorentina_logo.svg",
  "Real Sociedad": "https://upload.wikimedia.org/wikipedia/en/8/87/Real_Sociedad_logo.svg",
  "Villarreal": "https://upload.wikimedia.org/wikipedia/en/b/b9/Villarreal_CF_logo.svg",
  "Athletic Bilbao": "https://upload.wikimedia.org/wikipedia/en/9/98/Athletic_Club_Bilbao_logo.svg",
  "TSG Hoffenheim": "https://upload.wikimedia.org/wikipedia/en/e/e7/TSG_1899_Hoffenheim_logo.svg",
  "Wolfsburg": "https://upload.wikimedia.org/wikipedia/en/f/fd/VfL_Wolfsburg_Logo.svg",
  "Eintracht Frankfurt": "https://upload.wikimedia.org/wikipedia/en/d/d2/Eintracht_Frankfurt_Logo.svg",
  "Freiburg": "https://upload.wikimedia.org/wikipedia/en/d/d2/SC_Freiburg_logo.svg",
  "Monaco": "https://upload.wikimedia.org/wikipedia/en/9/92/AS_Monaco_FC_logo.svg",
  "Lyon": "https://upload.wikimedia.org/wikipedia/en/c/c1/Olympique_Lyonnais_logo.svg",
  "Marseille": "https://upload.wikimedia.org/wikipedia/en/1/12/Olympique_de_Marseille_logo.svg",
  "Lille": "https://upload.wikimedia.org/wikipedia/en/3/30/LOSC_Lille_logo.svg",
};
